export const ActionTypes = {
    SET_PRODUCTS: "SET_COINS",
    SELECTED_PRODUCT: "SELECTED_COIN",
    CURRENCY:"CURRENCY",
    SET_TRENDING_COINS:"SET_TRENDING_COINS",
    SET_HISTORICAL_DATA:"SET_HISTORICAL_DATA"
  };
  